Update build-tokens.yml

diff --git a/.github/workflows/build-tokens.yml b/.github/workflows/build-tokens.yml
--- a/.github/workflows/build-tokens.yml
+++ b/.github/workflows/build-tokens.yml
@@ -73,4 +73,17 @@ jobs:
         run: |
           git config user.name "GitHub Actions"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git push origin master
+          
+          # Add moved files to staging area
+          git add . || { echo "Failed adding files to staging area."; exit 1; }
+        
+          # Check if there are any changes to commit
+          if git diff-index --quiet HEAD --; then
+            echo "No changes to commit."
+          else
+            # Commit changes
+            git commit -m "Moved build artifacts from workflow (SHA: ${{ github.sha }})" || { echo "Failed committing changes."; exit 1; }
+            
+            # Push changes
+            git push origin master || { echo "Failed pushing changes."; exit 1; }
+          fi
