Update build-tokens.yml

diff --git a/.github/workflows/build-tokens.yml b/.github/workflows/build-tokens.yml
--- a/.github/workflows/build-tokens.yml
+++ b/.github/workflows/build-tokens.yml
@@ -6,6 +6,9 @@ on:
   pull_request:
     branches: [ main ]
 
+permissions:
+  contents: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -39,11 +42,50 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: my-artifacts
-          path: |
-            build/flutter/rekanesia-light-lime.dart
+          path: build/  # Pastikan folder ini adalah output dari build script Anda
 
-      - name: Archive code coverage results
-        uses: actions/upload-artifact@v4
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Download Artifacts
+        uses: actions/download-artifact@v4
         with:
-          name: build-output
-          path: build/my-artifacts.zip
+          name: my-artifacts
+          path: ./build  # Pastikan folder tujuan sama dengan yang diupload sebelumnya
+
+      - name: Create or Switch to master branch
+        run: |
+          git fetch origin
+          git checkout master || git checkout -b master
+
+      - name: Move Artifacts to Root
+        run: |
+          mv build/* .  # Pindahkan semua file dari folder build ke root
+
+      - name: Commit and Push changes
+        env:
+          PAT: ${{ secrets.ACCESS_TOKEN }}
+        run: |
+          git config user.name "GitHub Actions"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          
+          # Add moved files to staging area
+          git add . || { echo "Failed adding files to staging area."; exit 1; }
+        
+          # Check if there are any changes to commit
+          if git diff-index --quiet HEAD --; then
+            echo "No changes to commit."
+          else
+            # Commit changes
+            git commit -m "Moved build artifacts from workflow (SHA: ${{ github.sha }})" || { echo "Failed committing changes."; exit 1; }
+            
+            # Set up remote URL with token authentication
+            git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
+        
+            # Push changes
+            git push origin master || { echo "Failed pushing changes."; exit 1; }
+          fi
