Update build-tokens.yml

diff --git a/.github/workflows/build-tokens.yml b/.github/workflows/build-tokens.yml
--- a/.github/workflows/build-tokens.yml
+++ b/.github/workflows/build-tokens.yml
@@ -2,9 +2,9 @@ name: Build Tokens
 
 on:
   push:
-    branches: [ main ]
+    branches: [main]
   pull_request:
-    branches: [ main ]
+    branches: [main]
 
 permissions:
   contents: write
@@ -55,16 +55,7 @@ jobs:
         uses: actions/download-artifact@v4
         with:
           name: my-artifacts
-          path: ./build  # Pastikan folder tujuan sama dengan yang diupload sebelumnya
-
-      - name: Create or Switch to master branch
-        run: |
-          git fetch origin
-          git checkout master || git checkout -b master
-
-      - name: Move Artifacts to Root
-        run: |
-          mv build/* .  # Pindahkan semua file dari folder build ke root
+          path: ./  # Mengunduh langsung ke direktori saat ini tanpa perlu folder tambahan
 
       - name: Commit and Push changes
         env:
@@ -73,19 +64,19 @@ jobs:
           git config user.name "GitHub Actions"
           git config user.email "github-actions[bot]@users.noreply.github.com"
           
-          # Add moved files to staging area
-          git add . || { echo "Failed adding files to staging area."; exit 1; }
+          # Add all files to staging area
+          git add --all || { echo "Failed adding files to staging area."; exit 1; }
         
           # Check if there are any changes to commit
           if git diff-index --quiet HEAD --; then
             echo "No changes to commit."
           else
             # Commit changes
-            git commit -m "Moved build artifacts from workflow (SHA: ${{ github.sha }})" || { echo "Failed committing changes."; exit 1; }
+            git commit -m "Add build artifacts from workflow (SHA: ${{ github.sha }})" || { echo "Failed committing changes."; exit 1; }
             
             # Set up remote URL with token authentication
             git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${{ github.repository }}.git
         
             # Push changes
-            git push origin master || { echo "Failed pushing changes."; exit 1; }
+            git push origin HEAD:master || { echo "Failed pushing changes."; exit 1; }
           fi
